[supervisord]
nodaemon=true

[program:fastify]
command=npx tsx server/src/index.ts
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
environment=YTM_SERVICE_URL="http://localhost:8001",PORT=%(ENV_PORT)s,HOST=0.0.0.0,NODE_ENV=production

[program:ytm]
command=python ytm-service/app.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
environment=PORT=8001,HOST=0.0.0.0,YTM_LANGUAGE=es,YTM_LOCATION=MX